services:
  mariadb:
    image: "mariadb"
    restart: "on-failure:3"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "products"
    volumes:
      - "./data/mariadb:/var/lib/mysql"

  backend:
    build: "./backend"
    depends_on:
      - "mariadb"
    restart: "on-failure:3"
    environment:
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_ROOT_PASSWORD}"
      SPRING_SECURITY_JWT_SECRET_KEY: "${SECURITY_JWT_SECRET_KEY}"
      SPRING_SECURITY_JWT_EXPIRATION_TIME: "${SECURITY_JWT_EXPIRATION_TIME}"
      SPRING_SECURITY_SENDGRID_SECRET_KEY: "${SECURITY_SENDGRID_SECRET_KEY}"
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/products"
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8080"

  phpmyadmin:
    image: "phpmyadmin"
    depends_on:
      - "mariadb"
    restart: "on-failure:3"
    environment:
      PMA_HOST: "mariadb"
    ports:
      - "127.0.0.1:${PHPMYADMIN_EXTERNAL_PORT}:80"

  frontend:
    build: "./angular_frontend"
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:4200"
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: [ "ng", "serve", "--host", "0.0.0.0", "--proxy-config", "proxy.conf.json" ]
